<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<!-- Generated by The Webalizer  Ver. 2.23-08 -->
<!--                                          -->
<!-- Copyright 1997-2013  Bradford L. Barrett -->
<!--                                          -->
<!-- Distributed under the GNU GPL  Version 2 -->
<!--        Full text may be found at:        -->
<!--         http://www.webalizer.org         -->
<!--                                          -->
<!--  Give the power back to the programmers  -->
<!--   Support the Free Software Foundation   -->
<!--           (http://www.fsf.org)           -->
<!--                                          -->
<!-- *** Generated: 08-Feb-2019 23:10 KST *** -->


<HTML lang="ko">

<HEAD>
  <meta charset="utf-8">
  <TITLE>FLAGTAG</TITLE>
  <link rel="stylesheet" href="/css/header.css">
  <link rel="stylesheet" href="/css/loginHeader.css">
  <link rel="stylesheet" href="/css/mainFrame.css">


  <link href="https://fonts.googleapis.com/css?family=Nanum+Brush+Script&amp;subset=korean" rel="stylesheet">
  <style media="screen">
  * {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
  }
  </style>
</HEAD>

<body>
  <!--header
  #login이 되어 있는지에 따라서 다른 header 불러옴-->
  <?php
    session_start();
    if(!isset($_SESSION['is_login'])){

      include "view/header.html";
    }else{
      include "view/loginHeader.php";
    }
  ?>

  <main>
    <div id="mainframe" z-index="1">
      <?php
        if(isset($_GET['menu'])){
          include("view/".$_GET['menu'].".php");
        }
      ?>
    </div>
  </main>

</body>
