<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<!-- Generated by The Webalizer  Ver. 2.23-08 -->
<!--                                          -->
<!-- Copyright 1997-2013  Bradford L. Barrett -->
<!--                                          -->
<!-- Distributed under the GNU GPL  Version 2 -->
<!--        Full text may be found at:        -->
<!--         http://www.webalizer.org         -->
<!--                                          -->
<!--  Give the power back to the programmers  -->
<!--   Support the Free Software Foundation   -->
<!--           (http://www.fsf.org)           -->
<!--                                          -->
<!-- *** Generated: 08-Feb-2019 23:10 KST *** -->


<HTML lang="ko">

<HEAD>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style media="type/css">
    @-ms-viewport{width:device-width;}
    @-o-viewport{width:device-width;}
    @viewport{width:device-width;}
  </style>
  <TITLE>FLAGTAG</TITLE>
  <link rel="stylesheet" href="/css/header.css">
  <link rel="stylesheet" href="/css/loginHeader.css">
  <link rel="stylesheet" href="/css/mainFrame.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Nanum+Brush+Script&amp;subset=korean" rel="stylesheet">
  <!--나눔 폰트-->
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <style media="screen">
  * {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
  }
  body{
    font-family: 'NanumSquare', sans-serif;
  }
  </style>
</HEAD>

<body>
  <!--header
  #login이 되어 있는지에 따라서 다른 header 불러옴-->
  <?php
    session_start();
    if(!isset($_SESSION['is_login'])){
      include "view/header.html";
      if($_GET['menu']!='login' && $_GET['menu']!='join'){
        echo "<script> window.location.href = '../index.php?menu=login';</script>";
      }
    }
    else{
      include "view/loginHeader.php";
    }
  ?>

  <main>
    <div id="mainframe" z-index="1">
      <?php
        if(isset($_GET['menu'])){
          include("view/".$_GET['menu'].".php");
        }
      ?>
    </div>
  </main>

  <?php
    include "view/footer.html";
   ?>
  

</body>
